services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_TAG: $USER/$PROJECT_NAME:0.0.1-SNAPSHOT
  IMAGE_LATEST: $USER/$PROJECT_NAME:0.0.1-SNAPSHOT
  
image: docker:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - package
  - deploy

build_job:
  image: maven:3.6.3-jdk-11
  stage: build
  tags:
    - docker
  
  script:
    - echo "Maven compile started"
    - "mvn compile"

test_job:
  image: maven:3.6.3-jdk-11
  stage: test
  tags:
    - docker

  script:
    - echo "Maven test started"
    - "mvn test"

sonarcloud-check:
  image: maven:3.6.3-jdk-11
  stage: test
  tags:
    - docker
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn clean package sonar:sonar -Dsonar.projectKey=carvalhofg_sport-manager
  only:
    - master


package_job:
  image: maven:3.6.3-jdk-11
  stage: package
  tags:
    - docker

  script:
    - echo "Maven packaging started"
    - "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
  only:
    - master

deploy_job:
  image: docker:stable
  stage: deploy
  tags:
    - docker
  before_script:
    - echo "$PASSWORD" | docker login -u "$USER" "$CI_REGISTRY" --password-stdin
  script:
    - docker pull $IMAGE_LATEST || true
    - docker build --cache-from $IMAGE_LATEST -t $IMAGE_TAG -t $IMAGE_LATEST .
    - docker push $IMAGE_TAG
    - docker push $IMAGE_LATEST
  only:
    - master




